version: '3'
services:
  demo-app:
    build: .
    volumes:
      # - .dockervenv:/src/.venv
      - ./.kube/config:/root/.kube/config
    ports:
      - 8080:8080  # ホストマシンのポート8000を、docker内のポート8000に接続する