name: My Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-api:
    uses: ./.github/workflows/main.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    with:
      dockerfile_path: .
      ecr_repository: api
      image_tag: api
